version: "3"

services:
    python-analise-postgre:
        image: postgres:12
        container_name: "PYTHON-ANALISE-CRED-POSTGRE"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker123
        ports:
            - 5432:5432
        volumes:
            - volume-potgre-analise:/var/lib/postgresql/data:rw
            - volume-postgre-data-analise:/var/lib/postgresql/data:rw
        networks:
            - python-analise-network

    python-analise-pgadmin:
        image: dpage/pgadmin4:4.16
        container_name: "PYTHON-ANALISE-CRED-PGADMIN"
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 80:80
        volumes:
            - volume-pgadmin-analise:/pgadmin4:rw
            - volume-pgadmin-analise-lib:/var/lib/pgadmin:rw
            - volume-pgadmin-analise-certs:/certs:rw
        depends_on:
            - python-analise-postgre
        networks:
            - python-analise-network

networks:
    python-analise-network:
        driver: bridge

volumes:
    volume-potgre-analise:
    volume-postgre-data-analise:
    volume-pgadmin-analise:
    volume-pgadmin-analise-lib:
    volume-pgadmin-analise-certs: