# Generated by Django 2.2.4 on 2019-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANALISE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RENDA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDADE', models.IntegerField(null=True)),
                ('EMPRESTIMO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RESULTADO', models.IntegerField(null=True)),
            ],
        ),
    ]
